libhal/libhal-lpc40

- demos/float/CMakeLists.txt
- demos/float/float.cpp
- demos/float/libembeddedhal.tweaks.hpp
Total cost without floats is 480 bytes. With all floats costs and
`-mfloat-abi=soft` total size of the binary is 5024 bytes. So the
cost of floats is 4544.
> Cost of using float point

- demos/applications/adc.cpp
- demos/applications/blinker.cpp
- demos/applications/can.cpp
- demos/applications/gpio.cpp
- demos/applications/interrupt_pin.cpp
- demos/applications/uart.cpp
- include/liblpc40xx/adc.hpp
- include/liblpc40xx/can.hpp
- include/liblpc40xx/constants.hpp
- include/liblpc40xx/input_pin.hpp
- include/liblpc40xx/internal/gpio.hpp
- include/liblpc40xx/internal/pin.hpp
- include/liblpc40xx/interrupt_pin.hpp
- include/liblpc40xx/output_pin.hpp
- include/liblpc40xx/system_controller.hpp
- include/liblpc40xx/uart.hpp
- test_package/libhal.tweaks.hpp
- test_package/main.cpp
- tests/CMakeLists.txt
- tests/system_controller.test.cpp
- All factories now handle executing configure on the object rather than performing configuration in the constructor.
- Update demo applications to use correct result types
- Clean up some unneeded headers in various files
- Remove libxbitset and use hal::bit libraries
- Fix naming in test package
- Update irq numbers to reflect their unsigned event number rather than their signed version
- Add system_controller unit test file
> All ::get factories return result<T>

- include/liblpc40xx/interrupt_pin.hpp
Reduces memory usage from 2048 bytes to 1536 bytes, saving 512 bytes.
> :zap: Move interrupt_pin to hal::callback

- demos/CMakeLists.txt
- demos/conanfile.txt
The toolchain.cmake file was moved from libhal-armcortex to its own repo and package to allow toolchain and cmake files to change without affecting the version of the drivers.
> :plus: Add cmake-arm-embedded/0.1.0 to demos/

- demos/conanfile.txt
- 0.3.6 does not exist
- Bump version of cmake-arm-embedded to 0.1.1
> :arrow_down: Bring demo version down to 0.3.5

- conanfile.py
- demos/conanfile.txt
- include/libhal-lpc40xx/can.hpp
`can::configure()` should be calling `setup()` each time and not `configure_baud_rate()`. Once the CAN peripheral is enabled, then modifications to the clock rate settings is not possible. But setup() disables the peripheral first before setting up the clock rates.
- Bump version to 0.3.6
> :bug: Fix `can::configure()` changing nothing

- demos/CMakeLists.txt
No longer required to specify Debug and cmake_toolchain.cmake with the cmake command.
> :technologist: Simplify demo building

- conanfile.py
- demos/CMakeLists.txt
- demos/applications/adc.cpp
- demos/applications/can.cpp
- demos/applications/empty.cpp
- demos/applications/gpio.cpp
- demos/applications/interrupt_pin.cpp
- demos/conanfile.txt
- include/libhal-lpc40xx/adc.hpp
- include/libhal-lpc40xx/can.hpp
- include/libhal-lpc40xx/i2c.hpp
- include/libhal-lpc40xx/input_pin.hpp
- include/libhal-lpc40xx/output_pin.hpp
- include/libhal-lpc40xx/uart.hpp
- test_package/main.cpp
- tests/conanfile.txt
- tests/run.sh
- :arrow_up: Upgrade to libhal/[^1.0.0]. Using `^` to ensure that libhal-util can work any other library with a compatible major number of libhal.
- :arrow_up: Upgrade to libhal-util/[^1.0.0]. Using `^` to ensure that libhal-util can work any other library with a compatible major number of libhal.
- :arrow_up: Upgrade to libhal-armcortex/[^1.0.0]. Using `^` to ensure that libhal-util can work any other library with a compatible major number of libhal.
- :recycle: Refactor code to use latest libhal code
- :adhesive_bandage: Fix ordering of toolchain code in demos/CMakeLists.txt
- :fire: Remove demo/empty.cpp, because it does nothing and adds no value.
> :rocket: Launch version 1.0.0

- conanfile.py
- demos/conanfile.txt
- include/libhal-lpc40xx/i2c.hpp
- :bug: Correct pin mappings & function codes for i2c0 and i2c1
- :bug: Set pull resistor settings to "none" for all i2c ports
- :arrow_up: Bump version to 1.0.1
> :bug: Fix i2c pin mapping & configuration

- conanfile.py
- demos/conanfile.py
- :arrow_up: Bump libhal-armcortex/1.0.1 to fix issues with missing linker scripts from armcortex
- :arrow_up: Bump version to 1.1.1
> :recycle: Rename package to libhal-lpc

- conan/profiles/lpc40
- conan/profiles/lpc4072
- conan/profiles/lpc4074
- conan/profiles/lpc4076
- conan/profiles/lpc4078
- conan/profiles/lpc4088
Include cortex-m4 and cortex-m4f profiles in the lpc40 profiles. These profiles include the necessary compiler flags for lpc40 targets. libhal-armcortex's recipe is removing the compiler flags from the recipe as they are not propagated to all packages in an application.
> :wrench: Leverage libhal-armcortex profiles

- conanfile.py
- demos/conanfile.py
- demos/main.cpp
- src/uart_reg.hpp
Use the __ARM_FP macro to call as the
`hal::cortex_m::try_initialize_floating_point_unit()` function is actually unreliable due to the fact that vendor supplied floating point IP blocks do not require bits to be set in that field. Meaning that the function does not do as it is advertised.
NOTE: Deleted 2.0.0 version from package repo and moving version back to 2.0.0-alpha.1. This way we have an alpha release of 2.0.0 before doing a full 2.0.0 release.
Resolves #174
Resolves #171
> :bug: Fix FPU initialization for hard float demos

- CMakeLists.txt
- conanfile.py
- demos/CMakeLists.txt
- demos/conanfile.py
CMake only adds the `-g` debug info flag for the "Debug" build type. This makes sense for libraries deployed on a server or computer but not an embedded system. The elf file is not what is executed but the .bin or .hex file generated from it. Those generated files have all extra debug info eliminated. Because of this, each build type can have debug information without degrading performance or increasing code size. The benefit is that users can use an on chip debugger and step into this libraries APIs to inspect possible issues or hidden registers.
> :technologist: Add debug info to all builds

- conanfile.py
- demos/applications/uart.cpp
- demos/conanfile.py
- include/libhal-lpc40/uart.hpp
- src/uart.cpp
The interrupt handler uses a pointer to the original object, captured by a lambda. When the object is moved, the address is no longer valid. The interrupt handler setup must be called again in the move constructor to relocate the address to the new moved address.
Resolves #179
> :bug: Fix segfault when uart receives data

- CMakeLists.txt
- tests/CMakeLists.txt
Previously the unit tests built every source file in parallel with the main library building each source file. To prevent double building, unit test's CMakeLists.txt file now links against the libhal-lpc40 library.
> :zap: Improve unit test build time

- conanfile.py
- demos/conanfile.py
This support is required in order to disable linker script injection when an unfamiliar platform is used.
> :bricks: Support arbitrary platform names

- .github/workflows/ci.yml
- conanfile.py
Using cortex-m4 and cortex-m4f as the profiles rather than the chip's profile name. This reduces the prebuilt count from 6 to 2. There were only two versions of the prebuilt binaries and having additional profiles wastes space.
> :construction_worker: Reduce # of prebuilt binaries

- conanfile.py
- src/i2c.cpp
- src/i2c_reg.hpp
- Fix bug that caused `driver_transaction` to return early due to a prematurely entering `m_busy` state.
- Renamed `received_data_received_(n)ack` states to `received_data_transmitted_(n)ack`
> Fix I2C premature busy state bug

- .github/workflows/ci.yml
Releases trigger package uploads, so creating a release is redundant.
> :construction_worker: Remove "release" job

- .github/workflows/ci.yml
The 4.x.y branch scheme means that this repo will get the latest changes to the ci that does not include breaking changes.
> :construction_worker: Use ci/4.x.y version

- demos/CMakeLists.txt
- demos/main.cpp
Wrap malloc, free and their reentrent variants with empty functions to reduce code size. These functions are unused in the code base but due to the GCC ABI for virtual destructors and potentially due to Boost.LEAF introducing std::exception into the code base, these functions have been linked in.
> :zap: Optimize demo build size

- conanfile.py
- demos/conanfile.py
spi header is missing in 2.1.2, so bumping the version so the next version to capture the spi header.
> :bug: Fix missing spi header

- conanfile.py
- demos/CMakeLists.txt
- demos/applications/pwm.cpp
- demos/conanfile.py
- demos/main.cpp
- src/clock.cpp
- src/i2c.cpp
- src/input_pin.cpp
- src/interrupt_pin.cpp
- src/output_pin.cpp
- src/pwm.cpp
- test_package/CMakeLists.txt
- Simplifies building libhal libraries and packages
- By using the standard cmake utilities, upgrades are easily installed by bumping the libhal-cmake-util version number
- Utilizes clang-tidy
- Bump version to 2.1.4
> :art: Use cmake-util helper functions
